# Generated by Django 4.0.3 on 2022-06-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catregory',
            new_name='Category',
        ),
    ]
